In [1]:
import xgboost

In [2]:
import pandas as pd

In [3]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset=dataset.astype(int)

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [8]:
dependent=dataset[['charges']]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import GradientBoostingRegressor
param_grid={'loss':['squared_error', 'absolute_error', 'huber', 'quantile'],'criterion':['friedman_mse', 'squared_error'],
           'max_features':['sqrt', 'log2']}
grid=GridSearchCV(GradientBoostingRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

C:\Anaconda\Lib\site-packages\sklearn\ensemble\_gb.py:424: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=GradientBoostingRegressor(), n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'squared_error'],
                         'loss': ['squared_error', 'absolute_error', 'huber',
                                  'quantile'],
                         'max_features': ['sqrt', 'log2']},
             verbose=3)

In [10]:
re=grid.cv_results_
print("The R_score value for best parameter{}:".format(grid.best_params_))

The R_score value for best parameter{'criterion': 'friedman_mse', 'loss': 'squared_error', 'max_features': 'sqrt'}:

In [11]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_loss,param_max_features,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.149216,0.045777,0.007157,0.005333,friedman_mse,squared_error,sqrt,"{'criterion': 'friedman_mse', 'loss': 'squared...",0.881471,0.803692,0.889007,0.849213,0.862651,0.857207,0.030190,1
1,0.099723,0.016699,0.003443,0.003109,friedman_mse,squared_error,log2,"{'criterion': 'friedman_mse', 'loss': 'squared...",0.876799,0.799697,0.891921,0.850210,0.862518,0.856229,0.031524,3
2,0.313755,0.013382,0.004085,0.002710,friedman_mse,absolute_error,sqrt,"{'criterion': 'friedman_mse', 'loss': 'absolut...",0.874001,0.775302,0.847255,0.825253,0.846266,0.833615,0.033007,12
3,0.373719,0.085025,0.004348,0.005821,friedman_mse,absolute_error,log2,"{'criterion': 'friedman_mse', 'loss': 'absolut...",0.868022,0.774470,0.877937,0.814316,0.846905,0.836330,0.037838,11
4,0.563476,0.018686,0.006516,0.002498,friedman_mse,huber,sqrt,"{'criterion': 'friedman_mse', 'loss': 'huber',...",0.890018,0.788023,0.884574,0.845171,0.862775,0.854112,0.036715,5
5,0.423450,0.073426,0.002275,0.003037,friedman_mse,huber,log2,"{'criterion': 'friedman_mse', 'loss': 'huber',...",0.884894,0.792710,0.877611,0.843550,0.861906,0.852134,0.032932,8
6,0.324467,0.024118,0.006715,0.006836,friedman_mse,quantile,sqrt,"{'criterion': 'friedman_mse', 'loss': 'quantil...",0.538891,0.653060,0.617978,0.691739,0.682569,0.636847,0.055350,16
7,0.332763,0.014705,0.004333,0.003874,friedman_mse,quantile,log2,"{'criterion': 'friedman_mse', 'loss': 'quantil...",0.535859,0.659013,0.641781,0.709313,0.709526,0.651099,0.063612,15
8,0.088916,0.006863,0.002852,0.002510,squared_error,squared_error,sqrt,"{'criterion': 'squared_error', 'loss': 'square...",0.879307,0.800323,0.892308,0.850978,0.862378,0.857059,0.031691,2
9,0.084684,0.003580,0.005962,0.005540,squared_error,squared_error,log2,"{'criterion': 'squared_error', 'loss': 'square...",0.880618,0.802166,0.877507,0.849330,0.859224,0.853769,0.028272,6
10,0.309915,0.005776,0.003444,0.001995,squared_error,absolute_error,sqrt,"{'criterion': 'squared_error', 'loss': 'absolu...",0.877994,0.783805,0.869427,0.825812,0.835948,0.838597,0.033691,10
11,0.310184,0.008265,0.007678,0.004096,squared_error,absolute_error,log2,"{'criterion': 'squared_error', 'loss': 'absolu...",0.866358,0.783824,0.865773,0.829378,0.848422,0.838751,0.030629,9
12,0.410715,0.021940,0.002859,0.005718,squared_error,huber,sqrt,"{'criterion': 'squared_error', 'loss': 'huber'...",0.881877,0.787210,0.891945,0.843524,0.860815,0.853074,0.036959,7
13,0.433294,0.006411,0.000000,0.000000,squared_error,huber,log2,"{'criterion': 'squared_error', 'loss': 'huber'...",0.888142,0.793860,0.883601,0.846480,0.863915,0.855199,0.034078,4
14,0.339168,0.011271,0.006409,0.007853,squared_error,quantile,sqrt,"{'criterion': 'squared_error', 'loss': 'quanti...",0.560297,0.634790,0.716307,0.669932,0.724116,0.661088,0.059917,13
15,0.323469,0.020839,0.003179,0.006359,squared_error,quantile,log2,"{'criterion': 'squared_error', 'loss': 'quanti...",0.624173,0.609950,0.623630,0.689505,0.719561,0.653364,0.043149,14

In [12]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex_Male 0 or 1:"))
smoker_yes_input=float(input("Smoker_Yes 0 or 1:"))

Age:33
BMI:29
Children:3
Sex_Male 0 or 1:0
Smoker_Yes 0 or 1:0

In [13]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[7584.43492891]

C:\Anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(