In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
dataset=dataset.astype(int)

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [7]:
dependent=dataset[['charges']]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid={'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],'max_features':['sqrt', 'log2'],
           'n_estimators':[10,50,80,100]}
grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 32 candidates, totalling 160 fits

C:\Anaconda\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 50, 80, 100]},
             verbose=3)

In [9]:
re=grid.cv_results_
print("The R_score value for best parameter{}:".format(grid.best_params_))

The R_score value for best parameter{'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 50}:

In [10]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.066383,0.006065,0.005772,4.746288e-03,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.835167,0.758140,0.827215,0.806751,0.828200,0.811095,0.028125,31
1,0.273232,0.019343,0.013311,6.754875e-03,squared_error,sqrt,50,"{'criterion': 'squared_error', 'max_features':...",0.846968,0.776731,0.848710,0.822614,0.839953,0.826995,0.026773,21
2,0.503141,0.062042,0.015683,4.338161e-04,squared_error,sqrt,80,"{'criterion': 'squared_error', 'max_features':...",0.852865,0.772106,0.849736,0.823737,0.839693,0.827627,0.029560,17
3,0.494563,0.014041,0.021908,7.690110e-03,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.855273,0.779156,0.857778,0.823836,0.835929,0.830395,0.028523,6
4,0.053029,0.005811,0.006252,7.656875e-03,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.844607,0.751272,0.838394,0.814842,0.825260,0.814875,0.033437,28
5,0.245978,0.006715,0.015502,2.477192e-04,squared_error,log2,50,"{'criterion': 'squared_error', 'max_features':...",0.853549,0.771033,0.851914,0.821991,0.840012,0.827700,0.030495,15
6,0.392563,0.007601,0.015625,6.325960e-07,squared_error,log2,80,"{'criterion': 'squared_error', 'max_features':...",0.858348,0.779148,0.854861,0.819341,0.835680,0.829476,0.028817,9
7,0.488765,0.013394,0.019980,7.976225e-03,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.857493,0.778495,0.857779,0.823775,0.836874,0.830883,0.029197,3
8,0.055136,0.013499,0.009151,7.483219e-03,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.849259,0.750751,0.846898,0.810293,0.837253,0.818891,0.036772,26
9,0.243766,0.011437,0.015630,4.480747e-06,friedman_mse,sqrt,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.853026,0.767722,0.843396,0.825770,0.834599,0.824903,0.029991,24
10,0.384723,0.007563,0.016106,9.564682e-04,friedman_mse,sqrt,80,"{'criterion': 'friedman_mse', 'max_features': ...",0.853972,0.780303,0.850978,0.824901,0.834693,0.828969,0.026560,11
11,0.784711,0.231340,0.036987,2.222542e-02,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.852262,0.772638,0.853722,0.824761,0.839060,0.828489,0.029822,12
12,0.141912,0.010492,0.014618,1.978222e-03,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.847972,0.778918,0.844997,0.826426,0.819070,0.823476,0.024806,25
13,0.846719,0.085133,0.040207,1.580965e-02,friedman_mse,log2,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.855885,0.767639,0.853409,0.824480,0.837007,0.827684,0.032124,16
14,1.116322,0.052841,0.047042,1.002586e-02,friedman_mse,log2,80,"{'criterion': 'friedman_mse', 'max_features': ...",0.854858,0.771342,0.853035,0.824153,0.833472,0.827372,0.030335,20
15,1.215342,0.215171,0.040508,2.107488e-02,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.851242,0.774853,0.849905,0.821843,0.835867,0.826742,0.028059,23
16,0.390582,0.058822,0.013981,1.057075e-02,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.837208,0.748648,0.844445,0.828268,0.820785,0.815871,0.034550,27
17,2.202695,0.069939,0.033887,3.220593e-03,absolute_error,sqrt,50,"{'criterion': 'absolute_error', 'max_features'...",0.854030,0.775815,0.848154,0.826273,0.846588,0.830172,0.028747,8
18,3.305198,0.081683,0.052594,1.302785e-02,absolute_error,sqrt,80,"{'criterion': 'absolute_error', 'max_features'...",0.854869,0.776187,0.851547,0.829985,0.839660,0.830449,0.028534,5
19,4.207181,0.046810,0.059450,1.081841e-02,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.854428,0.771689,0.852577,0.829172,0.844902,0.830553,0.030750,4
20,0.430890,0.040607,0.015624,9.878801e-03,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.834822,0.753627,0.838615,0.808633,0.833836,0.813907,0.031958,30
21,2.059750,0.048487,0.028274,5.951500e-03,absolute_error,log2,50,"{'criterion': 'absolute_error', 'max_features'...",0.854583,0.778768,0.854183,0.828617,0.840860,0.831402,0.028014,1
22,3.568015,0.189906,0.044595,1.397521e-02,absolute_error,log2,80,"{'criterion': 'absolute_error', 'max_features'...",0.858214,0.772811,0.853379,0.824260,0.842452,0.830223,0.030987,7
23,4.309804,0.170158,0.059191,1.756449e-02,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.853373,0.777081,0.850355,0.826320,0.838710,0.829168,0.027738,10
24,0.156320,0.010102,0.015632,1.643560e-05,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.839514,0.746342,0.812758,0.815019,0.820391,0.806805,0.031664,32
25,0.737736,0.023237,0.031253,4.307400e-06,poisson,sqrt,50,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.854713,0.773587,0.854883,0.815209,0.836250,0.826928,0.030407,22
26,1.236590,0.046622,0.049421,5.535687e-03,poisson,sqrt,80,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.851994,0.770685,0.849687,0.822998,0.841971,0.827467,0.030166,18
27,1.493102,0.030165,0.050104,5.674961e-03,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.858260,0.775766,0.855404,0.824814,0.840841,0.831017,0.030082,2
28,0.170499,0.020920,0.010562,6.525903e-03,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.833478,0.758772,0.833429,0.808042,0.836424,0.814029,0.029480,29
29,0.731325,0.008244,0.028898,6.308877e-03,poisson,log2,50,"{'criterion': 'poisson', 'max_features': 'log2...",0.858343,0.768615,0.855742,0.826146,0.828067,0.827383,0.032306,19
30,1.291176,0.088003,0.043633,1.181928e-02,poisson,log2,80,"{'criterion': 'poisson', 'max_features': 'log2...",0.851325,0.775892,0.852640,0.824120,0.835279,0.827851,0.028051,14
31,1.366769,0.175243,0.045782,8.348908e-03,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.853441,0.773539,0.855176,0.822187,0.837508,0.828370,0.029917,13

In [11]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex_Male 0 or 1:"))
smoker_yes_input=float(input("Smoker_Yes 0 or 1:"))

Age:55
BMI:35
Children:4
Sex_Male 0 or 1:1
Smoker_Yes 0 or 1:1

In [12]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[44554.28]

C:\Anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(