In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
dataset=dataset.astype(int)

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [7]:
dependent=dataset[['charges']]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],'splitter':['best', 'random'],
           'max_features':['sqrt', 'log2']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [9]:
re=grid.cv_results_
print("The R_score value for best parameter{}:".format(grid.best_params_))

The R_score value for best parameter{'criterion': 'poisson', 'max_features': 'sqrt', 'splitter': 'best'}:

In [10]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005954,0.003829,0.007353,0.005241,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.711352,0.538863,0.701978,0.708349,0.745558,0.681220,0.072773,4
1,0.002408,0.002062,0.002202,0.004404,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.676381,0.612322,0.693656,0.661871,0.675358,0.663917,0.027701,8
2,0.006735,0.002777,0.004713,0.002547,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.634004,0.640492,0.639600,0.746535,0.689256,0.669977,0.043172,6
3,0.008569,0.005466,0.005833,0.005232,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.732991,0.608082,0.672520,0.682315,0.641424,0.667467,0.041819,7
4,0.011618,0.004240,0.002445,0.002281,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.630604,0.569085,0.738841,0.591038,0.674730,0.640860,0.060806,14
5,0.011339,0.003162,0.003964,0.003084,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.688994,0.594498,0.685336,0.656064,0.527310,0.630440,0.061687,15
6,0.008194,0.008448,0.002511,0.005021,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.689064,0.592603,0.693507,0.663362,0.718252,0.671358,0.043057,5
7,0.011750,0.010150,0.001777,0.003553,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.662611,0.507272,0.764912,0.563736,0.635057,0.626717,0.087965,16
8,0.024182,0.010456,0.003415,0.005070,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.693842,0.603505,0.615715,0.692824,0.701793,0.661536,0.042686,10
9,0.025368,0.004899,0.001296,0.001615,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.709648,0.677956,0.725669,0.656617,0.544397,0.662857,0.063929,9
10,0.026290,0.005112,0.003366,0.002878,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.717269,0.633822,0.731277,0.751054,0.685661,0.703816,0.040976,2
11,0.024020,0.003746,0.002959,0.002115,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.660810,0.583156,0.635661,0.688620,0.671983,0.648046,0.036732,12
12,0.006859,0.003458,0.004699,0.003350,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.753966,0.648408,0.639460,0.724383,0.759296,0.705102,0.051419,1
13,0.005686,0.003081,0.003163,0.003847,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.769116,0.581216,0.520693,0.672638,0.697048,0.648142,0.087577,11
14,0.007620,0.001649,0.003554,0.001920,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.683392,0.635255,0.712962,0.702280,0.714492,0.689676,0.029387,3
15,0.006784,0.001756,0.002943,0.001550,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.686681,0.559645,0.601177,0.695279,0.692944,0.647145,0.056119,13

In [11]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex_Male 0 or 1:"))
smoker_yes_input=float(input("Smoker_Yes 0 or 1:"))

Age:28
BMI:33
Children:3
Sex_Male 0 or 1:0
Smoker_Yes 0 or 1:0

In [12]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[5138.]

C:\Anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(